---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jamesdbloom/docker-java8-maven
    tag: "latest"

inputs:
- name: git-assets

run:
  path: git-assets/ci/tasks/test.sh
